name: atrons_v1
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  introduction_screen: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  flutter_custom_dialog: ^1.3.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  animated_theme_switcher: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  # connectivity_plus: ^3.0.3
  
  # cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.3
  # dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  # flutter_spinkit: ^5.2.0
  google_fonts: ^6.2.1
  path: ^1.8.2
  path_provider: ^2.0.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.1
  flutter_windowmanager: ^0.2.0
  vocsy_epub_viewer: ^3.0.0
  audio_video_progress_bar: ^2.0.3
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.28.0

  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1

dependency_overrides:
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # freezed: ^2.3.4
  # build_runner: ^2.0.3
  # dart_code_metrics: ^5.7.4

flutter_native_splash:
  color: '#45AE9F'
  color_dark: '#1D2733'
  image: 'assets/images/logo.png'

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# fonts:
#     - family:  MyFlutterApp
#     - asset: fonts/MyFlutterApp.ttf
