// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dTh59kbtESobfxwuyL9DwM8cWmUA70Q',
    appId: '1:892510091108:android:199be434e0b67d20606c71',
    messagingSenderId: '892510091108',
    projectId: 'atrons-5eef1',
    storageBucket: 'atrons-5eef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQO_pdhwhGnVbm3bUxEhDbo7PCqDLEDw',
    appId: '1:892510091108:ios:d69dbc756c53fd0b606c71',
    messagingSenderId: '892510091108',
    projectId: 'atrons-5eef1',
    storageBucket: 'atrons-5eef1.appspot.com',
    iosClientId: '892510091108-5nfeua21fui103103il58oifpobpr8ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.atronsV1',
  );
}
